#ifndef SAMCOIN_CHAINPARAMSSEEDS_H
#define SAMCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the samcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x0e,0xa1,0x1c,0xb2,0x1b,0xbc,
//    0x01,0x04,0x0e,0xa1,0x1c,0xb2,0x23,0x29,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x0e,0xa1,0x1c,0xb2,0x4a,0x39,
};
#endif // SAMCOIN_CHAINPARAMSSEEDS_H
